### ISSUE TITLE
Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: convictiontech/flutter_lottie

### ISSUE THREAD

**Issue by zhukeev** [CameronStuartSmith/flutter_lottie#26]
on Android 9 Xiaomi Note 5 

E/flutter (30881): 	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:91)
E/flutter (30881): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:96)
E/flutter (30881): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/flutter (30881): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/flutter (30881): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/flutter (30881): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/flutter (30881): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (30881): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter (30881): 	at android.os.Looper.loop(Looper.java:165)
E/flutter (30881): 	at android.app.ActivityThread.main(ActivityThread.java:6810)
E/flutter (30881): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (30881): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/flutter (30881): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by mathias21** [comment]
+1 here, in iOS simulator not working. Didnt try in Android. 
Loading animation from assets, properly declared in the pubspec.yaml like in example.
Just getting a blank white screen.

**Comment by yelkamel** [comment]
Me too
